### PR TITLE
A review form has been added to the product page.

### PR DESCRIPTION
**Pull request by zackha**
Hi @scottyzen, 

A form has been added to the product page for customers to rate and write reviews of the products. 
I tried to write the code as closely as possible to your coding standards, but I would appreciate it if you could review it. 
A few new words and sentences have been added to the English language file, and it would be great if @Zielgestalt could translate them into for german🙏.
If you would like to see how it looks, you can check out [this link](https://patch-woonuxt.netlify.app/).

Best regards,

Review Form

### CODE REVIEW

**Comment by scottyzen** [comment]
Hey @zackha. Great job, I love it. It looks very clean. I just tweaked the form slightly to make it more accessible. Other than that I'm happy to merge it. Have a look and let me know what you think. 🤙🏻

**Comment by Zielgestalt** [comment]
I'd love to add the missing German translations. But to be honest I have no idea how to contribute to an existing pr 🙈 Maybe you can help me with that? Or I can just add another pr with the missing translations.

**Comment by Zielgestalt** [comment]
And yes, I looks really great! Great job @zackha

**Comment by zackha** [comment]
> Hey @zackha. Great job, I love it. It looks very clean. I just tweaked the form slightly to make it more accessible. Other than that I'm happy to merge it. Have a look and let me know what you think. 🤙🏻

I thought I also wrote clean code, but you made it shine. Your editing has relieved me. You really live up to the phrase 'Soaking it all in'. 👌

**Comment by zackha** [comment]
> [Zielgestalt](/Zielgestalt)

@Zielgestalt

> Zielgestalt

Thank you very much for your support, @Zielgestalt. Your evaluation has motivated me.

**Comment by scottyzen** [comment]
Thank @zackha 😊 I just tweaked it, You had all the hard work done 👏🏻

Hey @Zielgestalt, If you have the git cli installed you can run `gh pr checkout 25`. You can find that on the top of the PR. See screenshot 👇
Screenshot 2023-03-31 at 21 25 52

**Pull request merged**
