### PR TITLE
get more than 10 color attribute in `ColorFilter.vue`

### PR DESCRIPTION
**Pull request by zackha**
image

### CODE REVIEW

**Comment by scottyzen** [comment]
Hi @zackha 

Can you change the wrapping to div to max-h-xs instead of h-xs and I can merge it then? Thanks

**Comment by scottyzen** [comment]
Thanks @zackha 👍🏻

**Comment by zackha** [comment]
I like your project very much. I will contribute as much as I can.

Stay awasome!

**Comment by scottyzen** [comment]
Super. Thanks a lot @zackha 😀

**Pull request merged**
